spring:
  datasource:
    url: jdbc:mysql://cmapdb.cdfonnhdltpr.ap-northeast-2.rds.amazonaws.com:3306/cmapDB
    username:
    password:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: dev # default profile
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          naver:
            client-id:
            client-secret:
            client-name: Naver
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    s3:
      bucket: ${ BUCKET }
    credentials:
      accessKey: ${ ACCESS-KEY }
      secretKey: ${ SECRET-KEY }
    region:
      static: ap-northeast-2
      stack:
        auto: false