
spring:
  datasource:
    url: jdbc:mysql://cmap-db.cdfonnhdltpr.ap-northeast-2.rds.amazonaws.com:3306/cmapDB
    username: cmap
    password: cmapcmap
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  profiles:
    active: dev # default profile
