spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/cmap
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    s3:
      bucket: ${ BUCKET }
    credentials:
      accessKey: ${ ACCESS-KEY }
      secretKey: ${ SECRET-KEY }