spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    s3:
      bucket: ${ BUCKET }
    credentials:
      accessKey: ${ ACCESS-KEY }
      secretKey: ${ SECRET-KEY }
    region:
      static: ${ STATIC }
    stack:
      auto: false

